### ISSUE TITLE
It looks like your Babel configuration specifies a module transformer.

### ISSUE THREAD

**Issue by thgh** [jlengstorf/learn-rollup#9] opened 2016-09-27 19:04 UTC
Got this error:

```
projects\learn-rollup>npm run dev
Error transforming projects\src\scripts\main.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
```

That page suggests this .babelrc

```
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

Even with that config, I couldn't get modules & es6 working.

**Comment by jlengstorf** [comment] 2016-09-30 22:08
Hey, @thgh — there was a discussion around this in #2, and it looks like you're using the same [config that solved the problem](https://github.com/jlengstorf/learn-rollup/issues/2#issuecomment-245573117) for most people.

Can you share the error message you're getting, along with the repo so I can check it out?

Thanks!

**Comment by gongph** [comment] 2016-10-18 02:16
Note: I use the window operating system. and node.js version is v6.2.0 and npm version is v3.8.9 . @jlengstorf

**Comment by jlengstorf** [comment] 2016-10-18 02:29
@thgh Did you get this worked out? I'm going to close this as a duplicate of #2, but if I'm wrong let me know and we'all get it sorted.

**Closed as completed by jlengstorf** 2016-10-18 02:29 UTC
Labels: duplicate
